services:
  - type: web
    name: hermit-md
    repo: https://github.com/A-d-i-t-h-y-a-n/hermit-md.git
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: VPS
        value: "true"
        required: false
      - key: SESSION_ID
        value: ""
        required: true
      - key: DATABASE_URL
        value: ""
        required: true
      - key: PREFIX
        value: "."
        required: false
      - key: SUDO
        value: "null"
        required: false
      - key: MODE
        value: "private"
        required: false
      - key: LOG_MSG
        value: "false"
        required: false
      - key: AUTO_STATUS_VIEW
        value: "false"
        required: false
      - key: READ_MSG
        value: "false"
        required: false
      - key: ALWAYS_ONLINE
        value: "false"
        required: false
      - key: START_MSG
        value: "true"
        required: false
