services:
  - type: web
    name: hermit-md
    repo: https://github.com/A-d-i-t-h-y-a-n/hermit-md.git
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: VPS
        required: true
        sync: false
      - key: SESSION_ID
        required: true
        sync: false
      - key: AUTH_FILE
        required: true
        sync: false
      - key: PREFIX
        required: true
        sync: false
      - key: SUDO
        required: true
        sync: false
      - key: MODE
        required: true
        sync: false
      - key: LOG_MSG
        required: true
        sync: false
      - key: AUTO_STATUS_VIEW
        required: true
        sync: false
      - key: READ_MSG
        required: true
        sync: false
      - key: ALWAYS_ONLINE
        required: true
        sync: false
      - key: START_MSG
        required: true
        sync: false
      - key: DATABASE_URL
        required: true
        sync: false
