services:
  - type: web
    name: hermit-md
    repo: https://github.com/A-d-i-t-h-y-a-n/hermit-md.git
    branch: main
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: VPS
        value: "true"
      - key: SESSION_ID
        sync: false
        generateValue: false
        required: true
        value: ""
      - key: DATABASE_URL
        sync: true
        value: ""
      - key: PREFIX
        sync: true
        value: "."
      - key: SUDO
        sync: true
        value: "null"
      - key: MODE
        value: "private"
      - key: LOG_MSG
        value: "false"
      - key: AUTO_STATUS_VIEW
        value: "false"
      - key: READ_MSG
        value: "false"
      - key: ALWAYS_ONLINE
        value: "false"
      - key: START_MSG
        value: "true"
